// Code generated by goctl. DO NOT EDIT.
package types

type Request struct {
}

type Response struct {
	UserName string `form:"user_name"`
}

type ExpandReq struct {
	Shorten string `form:"shorten"`
}

type ExpandResp struct {
	Url string `form:"url"`
}

type ShortenReq struct {
	Url string `form:"url"`
}

type ShortenResp struct {
	Shorten string `json:"shorten"`
}
